[package]
name = "fbxcel"
version = "0.2.1"
authors = ["YOSHIOKA Takuma <lo48576@hard-wi.red>"]
edition = "2018"
license = "MIT OR Apache-2.0"
readme = "README.md"
description = "Excellent FBX library"
repository = "https://github.com/lo48576/fbxcel"
keywords = ["FBX", "3D", "model"]

[features]
default = []

dom = ["indextree", "petgraph", "string-interner"]

[dependencies]
byteorder = "1"
indextree = { version = "3", optional = true }
libflate = "0.1"
log = "0.4.4"
petgraph = { version = "0.4", optional = true, default-features = false }
string-interner = { version = "0.7", optional = true, default-features = false }

[dev-dependencies]
env_logger = "0.6"

[badges]
maintenance = { status = "experimental" }
travis-ci = { repository = "lo48576/fbxcel" }

[[example]]
name = "dump-pull-parser-events"

[[example]]
name = "load-dom"
required-features = ["dom"]
